# CodeRabbit Configuration for Project Chimera
# AI Code Review Policy - Spec Alignment & Security Governance
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
early_access: false

# Review configuration
reviews:
  # Review profile: "chill" (balanced), "default" (standard), or "strict" (thorough)
  profile: "strict"
  # Request changes workflow - set to true to require approval before merge
  request_changes_workflow: true
  
  # High-level summary of changes
  high_level_summary: true
  # Include poem in reviews (optional, can be disabled)
  poem: false
  # Review status indicators
  review_status: true
  
  # Detailed review information
  review_details: true
  
  # Auto-review settings
  auto_review:
    enabled: true
    drafts: false

# Chat configuration
chat:
  auto_reply: true
